server:
  port: 8082

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/quickbite_order_db
    username: quickbite_user
    password: quickbite_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

security:
  api-key: qb-order-api-key-n3r8w5q1p6

restaurant:
  service:
    url: http://localhost:8081

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

logging:
  level:
    com.quickbite.order: DEBUG
    org.springframework.security: DEBUG
